<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Oleh : @Imroatus Tsaany Maghfira //@Teknik Informatika UIN Maulana Malik Ibrahim Malang //Dosen pengampu : @Prof. Dr. SUHARTONO, M.Kom" />


<title>Analisis Gambar Dalam Bentuk Matriks</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-sm-12 col-md-4 col-lg-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-sm-12 col-md-8 col-lg-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="program.html">Program</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Analisis Gambar Dalam Bentuk Matriks</h1>
<h4 class="author">Oleh : <span class="citation">@Imroatus</span> Tsaany Maghfira //<span class="citation">@Teknik</span> Informatika UIN Maulana Malik Ibrahim Malang //Dosen pengampu : <span class="citation">@Prof</span>. Dr. SUHARTONO, M.Kom</h4>
<h4 class="date">3/11/2021</h4>

</div>


<div id="instalasi-package" class="section level2">
<h2>Instalasi Package</h2>
<p>Langkah pertama disini yaitu menginstall package EBImage, kita ketikkan kode berikut pada bagian console</p>
<pre class="r"><code>#Install package
if (!requireNamespace(&quot;BiocManager&quot;, quietly = TRUE))
    install.packages(&quot;BiocManager&quot;)

BiocManager::install(&quot;EBImage&quot;)</code></pre>
<pre><code>## Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)</code></pre>
<pre><code>## Installing package(s) &#39;EBImage&#39;</code></pre>
<pre><code>## package &#39;EBImage&#39; successfully unpacked and MD5 sums checked</code></pre>
<pre><code>## Warning: cannot remove prior installation of package &#39;EBImage&#39;</code></pre>
<pre><code>## Warning in file.copy(savedcopy, lib, recursive = TRUE): problem
## copying D:\R-4.0.3\library\00LOCK\EBImage\libs\x64\EBImage.dll to D:
## \R-4.0.3\library\EBImage\libs\x64\EBImage.dll: Permission denied</code></pre>
<pre><code>## Warning: restored &#39;EBImage&#39;</code></pre>
<pre><code>## 
## The downloaded binary packages are in
##  C:\Users\HP\AppData\Local\Temp\RtmpagRkau\downloaded_packages</code></pre>
<pre><code>## Old packages: &#39;Matrix&#39;, &#39;tiff&#39;, &#39;xfun&#39;</code></pre>
<p>selanjutnya menentukan lokasi kerja, dimana kita memasukkan lokasi dari gambar yang akan saya gunakan kemudian memanggil package EBImage menggunakan perintah library.</p>
<pre class="r"><code>#set lokasi kerja
setwd(&quot;C:/Users/HP/Desktop&quot;)
#panggil package
library(EBImage)</code></pre>
</div>
<div id="importread-image" class="section level2">
<h2>Import/Read Image</h2>
<p>Untuk membaca gambar kita perlu menambahkan kode perintah readImage() dan memasukkan lokasi serta nama gambar. Perintah tersebut sudah ada pada package EBImage. Kemudian untuk menampilkan image menggunakan perintah display(namagambar). Kita menggunakan kode berikut:</p>
<pre class="r"><code>setwd(&quot;C:/Users/HP/Pictures&quot;)
library(EBImage)
Image &lt;- readImage(&#39;UIN.jpg&#39;)
display(Image)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>print(Image)</code></pre>
<pre><code>## Image 
##   colorMode    : Color 
##   storage.mode : double 
##   dim          : 275 184 3 
##   frames.total : 3 
##   frames.render: 1 
## 
## imageData(object)[1:5,1:6,1]
##           [,1]       [,2]       [,3]       [,4]       [,5]      [,6]
## [1,] 0.2235294 0.09411765 0.13333333 0.14117647 0.12156863 0.1529412
## [2,] 0.2392157 0.18431373 0.09803922 0.10980392 0.14509804 0.1411765
## [3,] 0.2745098 0.28235294 0.09803922 0.09019608 0.14901961 0.1294118
## [4,] 0.3058824 0.31764706 0.17647059 0.11372549 0.12156863 0.1254902
## [5,] 0.3254902 0.29411765 0.30196078 0.18039216 0.09411765 0.1372549</code></pre>
</div>
<div id="brightness" class="section level2">
<h2>Brightness</h2>
<p>Saya disini menambahkan 0.2 dan mengurangi 0.2 untuk intensitas gambar. Kemudian menampilkan kedua gambar menggunakan plot(images). Berikut kode untuk memanipulasi kecerahan gambar menggunakan tanda + dan - pada intensitas/kecerahan gambar:</p>
<pre class="r"><code>Image1 &lt;- Image + 0.2
Image2 &lt;- Image - 0.2
par(mfrow= c(1,2))
plot(Image1)
plot(Image2)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="adjusting-contrast" class="section level2">
<h2>Adjusting Contrast</h2>
<p>Kontras bisa dimanipulasi menggunakan perkalian berbeda dengan kecerahan menggunakan + dan -.Untuk gambar pertama dikali didengan 0.5 dan untuk gambar ke dua dikali dengan 2. Berikut kode untuk memberikan kontras pada gambar:</p>
<pre class="r"><code>Image3 &lt;- Image * 0.5
Image4 &lt;- Image * 2
par(mfrow= c(1,2))
plot(Image3)
plot(Image4)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="gamma-correction" class="section level2">
<h2>Gamma Correction</h2>
<p>Koreksi gamma adalah nama dari sebuah operasi nonlinier yang digunakan untuk kode dan decode luminance atau tristimulus nilai-nilai dalam video atau system gambar, ditentukan oleh power-law expression.</p>
<pre class="r"><code>Image5 &lt;- Image ^ 2
Image6 &lt;- Image ^ 0.7
par(mfrow=c(1,2))
plot(Image5)
plot(Image6)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="cropping" class="section level2">
<h2>Cropping</h2>
<p>Pada cropping kita akan memotong array dari pixel gambar, karena rentang gambar yang saya gunakan yaitu 275x184, jadi tidak boleh memotong lebih dari itu.</p>
<pre class="r"><code>display(Image[45:200, 20:80,])</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="spatial-transformation" class="section level2">
<h2>Spatial Transformation</h2>
<p>Kita bisa menggunakan rotate, translate flip yang telah disediakan oleh EBImage. Berikut codenya :</p>
<pre class="r"><code>Imagetr &lt;- translate(rotate(Image, 45), c(50,0))
display(Imagetr)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="color-management" class="section level2">
<h2>Color Management</h2>
<p>Karena array piksel memiliki tiga sumbu di dimensi, misalnya dalam kasus saya adalah 275 x 184 x 3. Sumbu ketiga adalah slot untuk tiga saluran: merah, hijau dan biru. Berikut kodenya :</p>
<pre class="r"><code>colorMode(Image) &lt;- Grayscale
display(Image)</code></pre>
<pre><code>## Only the first frame of the image stack is displayed.
## To display all frames use &#39;all = TRUE&#39;.</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>print(Image)</code></pre>
<pre><code>## Image 
##   colorMode    : Grayscale 
##   storage.mode : double 
##   dim          : 275 184 3 
##   frames.total : 3 
##   frames.render: 3 
## 
## imageData(object)[1:5,1:6,1]
##           [,1]       [,2]       [,3]       [,4]       [,5]      [,6]
## [1,] 0.2235294 0.09411765 0.13333333 0.14117647 0.12156863 0.1529412
## [2,] 0.2392157 0.18431373 0.09803922 0.10980392 0.14509804 0.1411765
## [3,] 0.2745098 0.28235294 0.09803922 0.09019608 0.14901961 0.1294118
## [4,] 0.3058824 0.31764706 0.17647059 0.11372549 0.12156863 0.1254902
## [5,] 0.3254902 0.29411765 0.30196078 0.18039216 0.09411765 0.1372549</code></pre>
<pre class="r"><code>colorMode(Image) &lt;- Color
display(Image)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
</div>
<div id="filtering" class="section level2">
<h2>filtering</h2>
<p>Untuk melakukan smoothing/mengaburkan menggunakan low-pass filter, dan menggunakan high-pass filter. Selain itu, kita juga akan menyelidiki median filter untuk menghilangkan noise.Berikut kode yang dapat kita gunakan untuk low-pass filter :</p>
<pre class="r"><code>fLow &lt;- makeBrush(21, shape= &#39;disc&#39;, step=FALSE)^2
fLow &lt;- fLow/sum(fLow)
Image.fLow &lt;- filter2(Image, fLow)
display(Image.fLow)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-10-1.png" width="672" /> Berikut kode untuk menggunakan high-pass filter :</p>
<pre class="r"><code>fHigh &lt;- matrix(1, nc = 3, nr = 3)
fHigh[2, 2] &lt;- -8
Image.fHigh &lt;- filter2(Image, fHigh)
display(Image.fHigh)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-11-1.png" width="672" /> kemudian kita akan mencoba menghilangkan noise pada gambar menggunakan medianFilter, berikut kodenya :</p>
<pre class="r"><code>setwd(&quot;C:/Users/HP/Pictures&quot;)
Image &lt;- readImage(&quot;UIN.jpg&quot;)
medFltr &lt;- medianFilter(Image, 1.1)
display(medFltr)</code></pre>
<p><img src="program_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="daftar-pustaka" class="section level2">
<h2>Daftar Pustaka</h2>
<p><a href="https://thinkstudioo.blogspot.com/2018/03/analisis-image-menggunakan-ebimage-di-r.html" class="uri">https://thinkstudioo.blogspot.com/2018/03/analisis-image-menggunakan-ebimage-di-r.html</a> <a href="https://thinkstudioo.blogspot.com/2018/03/analisis-image-menggunakan-ebimage-di-r_6.html" class="uri">https://thinkstudioo.blogspot.com/2018/03/analisis-image-menggunakan-ebimage-di-r_6.html</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
